### ISSUE TITLE
Can  somebody share extract_features.yaml?

### ISSUE THREAD

**Issue by Wolfman1219** [chomeyama/wavehax#1]
/wavehax/egs/jvs$ HYDRA_FULL_ERROR=1 wavehax-extract-features audio=data/scp/all.scp 

/home/deploy/second_disk/projects/TTS/NeuralSpeech/PriorGrad-acoustic/wavehax/wavehax/bin/extract_features.py:267: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path="config", config_name="extract_features")
Traceback (most recent call last):
  File "/home/deploy/miniconda3/envs/tts/lib/python3.10/site-packages/hydra/_internal/config_loader_impl.py", line 390, in _apply_overrides_to_config
    OmegaConf.update(cfg, key, value, merge=True)
  File "/home/deploy/miniconda3/envs/tts/lib/python3.10/site-packages/omegaconf/omegaconf.py", line 741, in update
    root.__setattr__(last_key, value)
  File "/home/deploy/miniconda3/envs/tts/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 337, in __setattr__
    raise e
  File "/home/deploy/miniconda3/envs/tts/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 334, in __setattr__
    self.__set_impl(key, value)
  File "/home/deploy/miniconda3/envs/tts/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 318, in __set_impl
    self._set_item_impl(key, value)
  File "/home/deploy/miniconda3/envs/tts/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 549, in _set_item_impl
    self._validate_set(key, value)
  File "/home/deploy/miniconda3/envs/tts/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 180, in _validate_set
    target = self._get_node(key) if key is not None else self
  File "/home/deploy/miniconda3/envs/tts/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 475, in _get_node
    self._validate_get(key)
  File "/home/deploy/miniconda3/envs/tts/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 164, in _validate_get
    self._format_and_raise(
  File "/home/deploy/miniconda3/envs/tts/lib/python3.10/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/home/deploy/miniconda3/envs/tts/lib/python3.10/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/home/deploy/miniconda3/envs/tts/lib/python3.10/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
omegaconf.errors.ConfigAttributeError: Key 'audio' is not in struct
    full_key: audio
    object_type=dict

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/deploy/miniconda3/envs/tts/bin/wavehax-extract-features", line 33, in <module>
    sys.exit(load_entry_point('wavehax', 'console_scripts', 'wavehax-extract-features')())
  File "/home/deploy/miniconda3/envs/tts/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/deploy/miniconda3/envs/tts/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/deploy/miniconda3/envs/tts/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/deploy/miniconda3/envs/tts/lib/python3.10/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/home/deploy/miniconda3/envs/tts/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/deploy/miniconda3/envs/tts/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/deploy/miniconda3/envs/tts/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 105, in run
    cfg = self.compose_config(
  File "/home/deploy/miniconda3/envs/tts/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 594, in compose_config
    cfg = self.config_loader.load_configuration(
  File "/home/deploy/miniconda3/envs/tts/lib/python3.10/site-packages/hydra/_internal/config_loader_impl.py", line 142, in load_configuration
    return self._load_configuration_impl(
  File "/home/deploy/miniconda3/envs/tts/lib/python3.10/site-packages/hydra/_internal/config_loader_impl.py", line 276, in _load_configuration_impl
    ConfigLoaderImpl._apply_overrides_to_config(config_overrides, cfg)
  File "/home/deploy/miniconda3/envs/tts/lib/python3.10/site-packages/hydra/_internal/config_loader_impl.py", line 392, in _apply_overrides_to_config
    raise ConfigCompositionException(
hydra.errors.ConfigCompositionException: Could not override 'audio'.
To append to your config use +audio=data/scp/all.scp

**Comment by chomeyama** [comment]
Would you try "audio_scp=<your_scp_file_path>" instead of "audio=<your_scp_file_path>" in your command?

**Comment by Wolfman1219** [comment]
Thank you it works.
